[package]
name = "sandbox-agent-openapi-gen"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
tracing.workspace = true
tracing-logfmt.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
sandbox-agent.workspace = true
serde_json.workspace = true
utoipa.workspace = true
